- hosts: webservers
  become: true
  tasks:

    - name: Enable Docker via Amazon Linux Extras
      command: amazon-linux-extras enable docker

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest NGINX image
      docker_image:
        name: nginx
        source: pull

    - name: Run NGINX container
      docker_container:
        name: nginx-container
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"